### ISSUE TITLE
WAHIS data processing steps

### ISSUE THREAD

**Issue by emmamendelsohn** [ecohealthalliance/open-rvfcast#44]
We want our model to represent how outbreaks affect other outbreaks, spatially and temporally. 

```[tasklist]
### Tasks
- [ ] Indicate if outbreak is initial or subsequent outbreak.  Need to define this, when is an outbreak "new" or a result of spread.
- [ ] https://github.com/ecohealthalliance/open-rvfcast/issues/50
- [ ] https://github.com/ecohealthalliance/open-rvfcast/issues/60
- [ ] Create fields for distance to nearest outbreak in last 2, 4, 6, 12, etc weeks. This will be a tuning parameter in the model. We will select one. Variable represents spread likelihood from recent/ongoing outbreaks.
- [ ] Create fields for distance to nearest outbreak prior to 2, 4, 6, 12 etc weeks. The threshold will be selected based on turning from task above. Variable to represent immunity.
```
Note: Outcome variable should not include wildlife, just livestock, but past and adjacent outbreaks should include wildlife cases as important for predicting outbreaks in livestock.

**Comment by emmamendelsohn** [comment]
Closing this as it is largely addressed with immunity effort. Will make separate issue for the note.
