### ISSUE TITLE
Planning spatial resolution of the model

### ISSUE THREAD

**Issue by emmamendelsohn** [ecohealthalliance/open-rvfcast#45]
Plan to train model on 52 districts, and can aggregate or subdivide as needed to account for differences in population/area. 

Build out workflow to allow various spatial resolutions and to facilitate comparison
```[tasklist]
### Tasks
- [ ] https://github.com/ecohealthalliance/open-rvfcast/issues/52
- [ ] https://github.com/ecohealthalliance/open-rvfcast/issues/53
- [ ] Figure out ADM-based spatial cross-validation
```
