### ISSUE TITLE
Farmer and stakeholder surveys

### ISSUE THREAD

**Issue by emmamendelsohn** [ecohealthalliance/open-rvfcast#47]
```[tasklist]
### Tasks
- [ ] Develop AirTable form for survey
- [ ] Ask Jack to circulate to meeting attendees
- [ ] Input results from paper surveys
- [ ] Summarize results quantitively and qualitatively (ie take home messages and next steps)
```

**Comment by emmamendelsohn** [comment]
[Early_Warning_Stakeholder_Survey.docx](https://github.com/ecohealthalliance/open-rvfcast/files/12834261/Early_Warning_Stakeholder_Survey.docx)
