### ISSUE TITLE
Next Steps

### ISSUE THREAD

**Issue by n8layman** [ecohealthalliance/open-rvfcast#86]
Goals: Setting up prediction pipeline next biggest goal.
    i. Incrementally download what we need for forecasting.
    ii. Get familiar with data sources 

  1. Emma: Focus on training pipeline
  2. Nate: Focus on engineering components and getting up to speed
  3. Noam: Setting up static and immune layer issues
  4. Mindy: Wellcome trust paperwork. PI transfer. Project administrative folder
  
  https://github.com/orgs/ecohealthalliance/projects/17?query=is%3Aopen+sort%3Aupdated-desc

```[tasklist]
### Tasks
- [ ] Full model run as is
- [ ] Cross validation finalized
- [ ] Integration of static data sets (soil type, elevation, aspect)
- [ ] Optimization e.g. immune layer (deferred).
- [ ] Model performance metric decisions
- [ ] Report structure
```
@noamross @emmamendelsohn @rostal @n8layman

**Comment by emmamendelsohn** [comment]
No longer planned for June but leaving this open as next steps

**Comment by emmamendelsohn** [comment]
Actually closing to cover under #91
